version: '3.1'
services:
    jenkins:
        image: jenkins/jenkins:latest
        restart: always
        container_name: jenkins
        ports:
            - 8080:8080
        user: root
        volumes:
            - /opt/jenkins/home:/var/jenkins_home
            - /etc/localtime:/etc/localtime
      
    gogs:
        image: gogs/gogs:latest
        restart: always
        container_name: gogs
        ports:
            - 80:3000
            - "2222:22"
        volumes:
            - /opt/gogs:/data
        depends_on: 
            - postgres

    postgres:
        image: postgres:11.6
        restart: always
        container_name: postgres
        ports:
            - 5432:5432
        environment: 
            - POSTGRES_PASSWORD=${PASSWD}
            - POSTGRES_DB=gogs
        volumes:
            - /opt/postgresqldb/data:/var/lib/postgresql/data
            - /etc/localtime:/etc/localtime
        